---
- name: INstall & deploy apache web server.
  hosts: prod 
  tasks:
   - name: Install the latest version of Apache
     ansible.builtin.yum:
       name: httpd
       state: latest 

   - name: Start service httpd, if not started
     ansible.builtin.service:
       name: httpd
       state: started
       enabled: true 

   - name: Install the latest version of firewalld.
     ansible.builtin.yum:
       name: firewalld
       state: latest 

   - name: Start service firewalld, if not started
     ansible.builtin.service:
       name: firewalld
       state: started
       enabled: true 

   - name: permit traffic in default zone for https service
     ansible.posix.firewalld:
       service: http
       permanent: yes
       immediate: true
       state: enabled

   - name: Deploying application - index.html 
     ansible.builtin.copy:
       content: "This is my 1st web page !!! \n"
       dest: /var/www/html/index.html 

- name: Validation - play 2nd 
  hosts: localhost
  become: false 
  tasks:
    - name: Check that a page returns a status 200.
      ansible.builtin.uri:
         url: http://servera.lab.example.com
         return_content: yes
         status_code: 200
 
